//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionRoss3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public int VendingId { get; set; }
        public int ProductId { get; set; }
        public string Quantity { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int MethodPayId { get; set; }
    
        public virtual MethodPay MethodPay { get; set; }
        public virtual Product Product { get; set; }
        public virtual Vending Vending { get; set; }
    }
}
