//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionRoss3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int VendingId { get; set; }
        public System.DateTime DateService { get; set; }
        public string DescriptionError { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual Vending Vending { get; set; }
    }
}
